name: Validate Data

on:
  pull_request:

jobs:
  validate-data:
    env:
      DATABASE_URL: postgresql://alex@localhost:5432/alex?schema=public
      JWT_SECRET: y0zSUTQ3AKqEskP849JukEI5f2AvDSmqRuxqaWfQXQSRcd4JR3RZtmFFrwET8gA/sh/+d3CwrkFVuIEdhRIVflsXE3i6hfF5Ac8YeQt/wZ6XVi+ixwWgu+C3Xek0g7B2uQj3YP8JB85JLLKq1u5U98Q/AGVlNc1r98mu+gvVWCkgAfYtAWH8RB65iZ8hE2vV93ULK4I5yMlncOb4TkAbgCfoz+rfTourYBkbsQ==%
      HASH_SECRET: V1/JS9JNHo964C6toWBc/vsp4/i08O/qDqA4+Hf+m3c1i9TmQz8ej1QHFL/hGb15cP6ySsl+Sjm8H3nhAn1G8UV8bThhMlYWVJuUtL5XkNkYaWuOf2fgeNWJX1tF3JOJrZtA38OvH/oB2m6jf3N7MiXAmQQX7ZuePuGkJNr3TMQM7HF1b27aq7m9BqWhmKOxemgB+9OcnaQwT0xrogh/QMAwHnzyZa/yCQR/yA==
      APP_ENV: test
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn
      - run: yarn build:only
      - run: yarn test